/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as BuyrpcRouteImport } from './routes/buyrpc'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PaymentInstructionsRouteImport } from './routes/payment-instructions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReferEarnRouteImport } from './routes/refer-earn'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as AdminPanelRouteImport } from './routes/admin/_panel'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminRegisterRouteImport } from './routes/admin/register'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as AdminPanelActivationsRouteImport } from './routes/admin/_panel/activations'
import { Route as AdminPanelAuditRouteImport } from './routes/admin/_panel/audit'
import { Route as AdminPanelDashboardRouteImport } from './routes/admin/_panel/dashboard'
import { Route as AdminPanelNotificationsRouteImport } from './routes/admin/_panel/notifications'
import { Route as AdminPanelPaymentsRouteImport } from './routes/admin/_panel/payments'
import { Route as AdminPanelPushRouteImport } from './routes/admin/_panel/push'
import { Route as AdminPanelReferralsRouteImport } from './routes/admin/_panel/referrals'
import { Route as AdminPanelTransactionsRouteImport } from './routes/admin/_panel/transactions'
import { Route as AdminPanelWithdrawalsRouteImport } from './routes/admin/_panel/withdrawals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyrpcRoute = BuyrpcRouteImport.update({
  id: '/buyrpc',
  path: '/buyrpc',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentInstructionsRoute = PaymentInstructionsRouteImport.update({
  id: '/payment-instructions',
  path: '/payment-instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferEarnRoute = ReferEarnRouteImport.update({
  id: '/refer-earn',
  path: '/refer-earn',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin/_panel',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelActivationsRoute = AdminPanelActivationsRouteImport.update({
  id: '/activations',
  path: '/activations',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelAuditRoute = AdminPanelAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelDashboardRoute = AdminPanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelNotificationsRoute = AdminPanelNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelPaymentsRoute = AdminPanelPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelPushRoute = AdminPanelPushRouteImport.update({
  id: '/push',
  path: '/push',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelReferralsRoute = AdminPanelReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelTransactionsRoute = AdminPanelTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelWithdrawalsRoute = AdminPanelWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminPanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/broadcast': typeof BroadcastRoute
  '/buyrpc': typeof BuyrpcRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/payment-instructions': typeof PaymentInstructionsRoute
  '/profile': typeof ProfileRoute
  '/refer-earn': typeof ReferEarnRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/withdraw': typeof WithdrawRoute
  '/admin': typeof AdminPanelRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/admin/activations': typeof AdminPanelActivationsRoute
  '/admin/audit': typeof AdminPanelAuditRoute
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/notifications': typeof AdminPanelNotificationsRoute
  '/admin/payments': typeof AdminPanelPaymentsRoute
  '/admin/push': typeof AdminPanelPushRoute
  '/admin/referrals': typeof AdminPanelReferralsRoute
  '/admin/transactions': typeof AdminPanelTransactionsRoute
  '/admin/withdrawals': typeof AdminPanelWithdrawalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/broadcast': typeof BroadcastRoute
  '/buyrpc': typeof BuyrpcRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/payment-instructions': typeof PaymentInstructionsRoute
  '/profile': typeof ProfileRoute
  '/refer-earn': typeof ReferEarnRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/withdraw': typeof WithdrawRoute
  '/admin': typeof AdminPanelRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/admin/activations': typeof AdminPanelActivationsRoute
  '/admin/audit': typeof AdminPanelAuditRoute
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/notifications': typeof AdminPanelNotificationsRoute
  '/admin/payments': typeof AdminPanelPaymentsRoute
  '/admin/push': typeof AdminPanelPushRoute
  '/admin/referrals': typeof AdminPanelReferralsRoute
  '/admin/transactions': typeof AdminPanelTransactionsRoute
  '/admin/withdrawals': typeof AdminPanelWithdrawalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/broadcast': typeof BroadcastRoute
  '/buyrpc': typeof BuyrpcRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/payment-instructions': typeof PaymentInstructionsRoute
  '/profile': typeof ProfileRoute
  '/refer-earn': typeof ReferEarnRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/_panel': typeof AdminPanelRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/admin/_panel/activations': typeof AdminPanelActivationsRoute
  '/admin/_panel/audit': typeof AdminPanelAuditRoute
  '/admin/_panel/dashboard': typeof AdminPanelDashboardRoute
  '/admin/_panel/notifications': typeof AdminPanelNotificationsRoute
  '/admin/_panel/payments': typeof AdminPanelPaymentsRoute
  '/admin/_panel/push': typeof AdminPanelPushRoute
  '/admin/_panel/referrals': typeof AdminPanelReferralsRoute
  '/admin/_panel/transactions': typeof AdminPanelTransactionsRoute
  '/admin/_panel/withdrawals': typeof AdminPanelWithdrawalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/broadcast'
    | '/buyrpc'
    | '/community'
    | '/dashboard'
    | '/history'
    | '/payment-instructions'
    | '/profile'
    | '/refer-earn'
    | '/success'
    | '/support'
    | '/welcome'
    | '/withdraw'
    | '/admin'
    | '/admin/login'
    | '/admin/register'
    | '/receipt/$id'
    | '/admin/activations'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/push'
    | '/admin/referrals'
    | '/admin/transactions'
    | '/admin/withdrawals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/broadcast'
    | '/buyrpc'
    | '/community'
    | '/dashboard'
    | '/history'
    | '/payment-instructions'
    | '/profile'
    | '/refer-earn'
    | '/success'
    | '/support'
    | '/welcome'
    | '/withdraw'
    | '/admin'
    | '/admin/login'
    | '/admin/register'
    | '/receipt/$id'
    | '/admin/activations'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/push'
    | '/admin/referrals'
    | '/admin/transactions'
    | '/admin/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/broadcast'
    | '/buyrpc'
    | '/community'
    | '/dashboard'
    | '/history'
    | '/payment-instructions'
    | '/profile'
    | '/refer-earn'
    | '/success'
    | '/support'
    | '/welcome'
    | '/withdraw'
    | '/admin/_panel'
    | '/admin/login'
    | '/admin/register'
    | '/receipt/$id'
    | '/admin/_panel/activations'
    | '/admin/_panel/audit'
    | '/admin/_panel/dashboard'
    | '/admin/_panel/notifications'
    | '/admin/_panel/payments'
    | '/admin/_panel/push'
    | '/admin/_panel/referrals'
    | '/admin/_panel/transactions'
    | '/admin/_panel/withdrawals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  BroadcastRoute: typeof BroadcastRoute
  BuyrpcRoute: typeof BuyrpcRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  PaymentInstructionsRoute: typeof PaymentInstructionsRoute
  ProfileRoute: typeof ProfileRoute
  ReferEarnRoute: typeof ReferEarnRoute
  SuccessRoute: typeof SuccessRoute
  SupportRoute: typeof SupportRoute
  WelcomeRoute: typeof WelcomeRoute
  WithdrawRoute: typeof WithdrawRoute
  AdminPanelRoute: typeof AdminPanelRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyrpc': {
      id: '/buyrpc'
      path: '/buyrpc'
      fullPath: '/buyrpc'
      preLoaderRoute: typeof BuyrpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-instructions': {
      id: '/payment-instructions'
      path: '/payment-instructions'
      fullPath: '/payment-instructions'
      preLoaderRoute: typeof PaymentInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer-earn': {
      id: '/refer-earn'
      path: '/refer-earn'
      fullPath: '/refer-earn'
      preLoaderRoute: typeof ReferEarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel': {
      id: '/admin/_panel'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel/activations': {
      id: '/admin/_panel/activations'
      path: '/activations'
      fullPath: '/admin/activations'
      preLoaderRoute: typeof AdminPanelActivationsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/audit': {
      id: '/admin/_panel/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminPanelAuditRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/dashboard': {
      id: '/admin/_panel/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminPanelDashboardRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/notifications': {
      id: '/admin/_panel/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminPanelNotificationsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/payments': {
      id: '/admin/_panel/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPanelPaymentsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/push': {
      id: '/admin/_panel/push'
      path: '/push'
      fullPath: '/admin/push'
      preLoaderRoute: typeof AdminPanelPushRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/referrals': {
      id: '/admin/_panel/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminPanelReferralsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/transactions': {
      id: '/admin/_panel/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminPanelTransactionsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/withdrawals': {
      id: '/admin/_panel/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminPanelWithdrawalsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
  }
}

interface AdminPanelRouteChildren {
  AdminPanelActivationsRoute: typeof AdminPanelActivationsRoute
  AdminPanelAuditRoute: typeof AdminPanelAuditRoute
  AdminPanelDashboardRoute: typeof AdminPanelDashboardRoute
  AdminPanelNotificationsRoute: typeof AdminPanelNotificationsRoute
  AdminPanelPaymentsRoute: typeof AdminPanelPaymentsRoute
  AdminPanelPushRoute: typeof AdminPanelPushRoute
  AdminPanelReferralsRoute: typeof AdminPanelReferralsRoute
  AdminPanelTransactionsRoute: typeof AdminPanelTransactionsRoute
  AdminPanelWithdrawalsRoute: typeof AdminPanelWithdrawalsRoute
}

const AdminPanelRouteChildren: AdminPanelRouteChildren = {
  AdminPanelActivationsRoute: AdminPanelActivationsRoute,
  AdminPanelAuditRoute: AdminPanelAuditRoute,
  AdminPanelDashboardRoute: AdminPanelDashboardRoute,
  AdminPanelNotificationsRoute: AdminPanelNotificationsRoute,
  AdminPanelPaymentsRoute: AdminPanelPaymentsRoute,
  AdminPanelPushRoute: AdminPanelPushRoute,
  AdminPanelReferralsRoute: AdminPanelReferralsRoute,
  AdminPanelTransactionsRoute: AdminPanelTransactionsRoute,
  AdminPanelWithdrawalsRoute: AdminPanelWithdrawalsRoute,
}

const AdminPanelRouteWithChildren = AdminPanelRoute._addFileChildren(
  AdminPanelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  BroadcastRoute: BroadcastRoute,
  BuyrpcRoute: BuyrpcRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  PaymentInstructionsRoute: PaymentInstructionsRoute,
  ProfileRoute: ProfileRoute,
  ReferEarnRoute: ReferEarnRoute,
  SuccessRoute: SuccessRoute,
  SupportRoute: SupportRoute,
  WelcomeRoute: WelcomeRoute,
  WithdrawRoute: WithdrawRoute,
  AdminPanelRoute: AdminPanelRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  ReceiptIdRoute: ReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
